#!/usr/bin/env python3

import subprocess


svc = input("Please enter command you want to execute:\n")

service_check = subprocess.call(["ps","-C",svc])

if(service_check == 0):
  print("The service is  running")
else:
  print("The service is not running")
  print("starting "+ svc+"...")
try:
  subprocess.call([svc])
except:
  print("Command not Found!!!")
  try:
    print("trying to download........")
    subprocess.call(["sudo","apt","update"])
    subprocess.call(["sudo","apt","upgrade"])
    subprocess.call(["sudo","apt","install",svc])
  except:
    print("Invalid Command!!!")
